- name: Apply all Kubernetes manifests
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    kubeconfig: ../Infrastructure/terraform/kubeconfig
    base: "../k8s_manifests"

  tasks:

    - name: Add ingress-nginx helm repo
      community.kubernetes.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx

    - name: Install NGINX Ingress Controller
      community.kubernetes.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        kubeconfig: "{{ kubeconfig }}"

    - name: Add Jetstack helm repo
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Install Cert-Manager
      community.kubernetes.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        version: v1.12.0
        kubeconfig: "{{ kubeconfig }}"
        values:
          installCRDs: true
