- name: Apply all Kubernetes manifests
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    kubeconfig: ../Infrastructure/terraform/kubeconfig
    base: "../k8s_manifests"

  tasks:

    - name: Add ingress-nginx helm repo
      community.kubernetes.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx

    - name: Install NGINX Ingress Controller via helm command
      ansible.builtin.command:
        cmd: >
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
          --namespace ingress-nginx --create-namespace
          --kubeconfig {{ kubeconfig }}

    - name: Add Jetstack helm repo
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Install Cert-Manager via helm command
      ansible.builtin.command:
        cmd: >
          helm upgrade --install cert-manager jetstack/cert-manager
          --namespace cert-manager
          --create-namespace
          --kubeconfig {{ kubeconfig }}
          --version v1.12.0
          --set installCRDs=true
          --set webhook.namespaceSelector={}
    
    
    
